export default function Head() {
	return (
		<>
			<title>New Chat</title>
			<meta content="width=device-width, initial-scale=1" name="viewport" />
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="https://pipedream.com/s.v0/app_mWnhBo/logo/orig" />
		</>
	);
}
